name = "sandbot-membership"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespaces
[[kv_namespaces]]
binding = "MEMBERS"
id = "1231f837b9cb4014ad8fdf8743770257"

[[kv_namespaces]]
binding = "CODES"
id = "c5d2380a4ea24710b974d112a73730d2"

# Environment variables
[vars]
ALLOWED_ORIGIN = "https://sandmark78.github.io"
